// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBfFehHGecBXSwMs0H-1IWciLXm6mBhY',
    appId: '1:215736120066:web:58fc71d4f0dd1f9900481b',
    messagingSenderId: '215736120066',
    projectId: 'duan1-8d607',
    authDomain: 'duan1-8d607.firebaseapp.com',
    storageBucket: 'duan1-8d607.appspot.com',
    measurementId: 'G-SRZKCSQNE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmTChpzZbzgpLdpIkyQlmxP6nTUrXHqM',
    appId: '1:215736120066:android:d270e1d4c3f0038700481b',
    messagingSenderId: '215736120066',
    projectId: 'duan1-8d607',
    storageBucket: 'duan1-8d607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofTQpEz6x408itu5bu17-MoOgZzAvrzI',
    appId: '1:215736120066:ios:d09101cef578c82f00481b',
    messagingSenderId: '215736120066',
    projectId: 'duan1-8d607',
    storageBucket: 'duan1-8d607.appspot.com',
    iosBundleId: 'com.example.duammoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCofTQpEz6x408itu5bu17-MoOgZzAvrzI',
    appId: '1:215736120066:ios:d09101cef578c82f00481b',
    messagingSenderId: '215736120066',
    projectId: 'duan1-8d607',
    storageBucket: 'duan1-8d607.appspot.com',
    iosBundleId: 'com.example.duammoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBfFehHGecBXSwMs0H-1IWciLXm6mBhY',
    appId: '1:215736120066:web:250b3837ccbdf31e00481b',
    messagingSenderId: '215736120066',
    projectId: 'duan1-8d607',
    authDomain: 'duan1-8d607.firebaseapp.com',
    storageBucket: 'duan1-8d607.appspot.com',
    measurementId: 'G-0WHGWL48X7',
  );
}
